### ISSUE TITLE
Improve error handling in demo

### ISSUE THREAD

**Issue by abraham** [abraham/twitteroauth#316]
```
2015-02-20T05:40:01.339495+00:00 app[web.1]: [20-Feb-2015 05:40:01 UTC] PHP Fatal error:  Uncaught exception 'Abraham\TwitterOAuth\TwitterOAuthException' with message 'Request timed out.' in /app/vendor/abraham/twitteroauth/src/TwitterOAuth.php:311
2015-02-20T05:40:01.549171+00:00 app[web.1]: 10.101.131.90 - - [20/Feb/2015:05:40:01 +0000] "GET /favicon.ico HTTP/1.1" 404 209 "-" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.53 Safari/537.36"
2015-02-20T05:40:01.339557+00:00 app[web.1]: Stack trace:
2015-02-20T05:40:01.339816+00:00 app[web.1]: #0 /app/vendor/abraham/twitteroauth/src/TwitterOAuth.php(251): Abraham\TwitterOAuth\TwitterOAuth->request('https://api.twi...', 'POST', 'Authorization: ...', Array)
2015-02-20T05:40:01.340033+00:00 app[web.1]: #1 /app/vendor/abraham/twitteroauth/src/TwitterOAuth.php(134): Abraham\TwitterOAuth\TwitterOAuth->oAuthRequest('https://api.twi...', 'POST', Array)
2015-02-20T05:40:01.340316+00:00 app[web.1]:   thrown in /app/vendor/abraham/twitteroauth/src/TwitterOAuth.php on line 311
2015-02-20T05:40:01.340180+00:00 app[web.1]: #2 /app/callback.php(27): Abraham\TwitterOAuth\TwitterOAuth->oauth('oauth/access_to...', Array)
2015-02-20T05:40:01.340198+00:00 app[web.1]: #3 {main}
2015-02-20T05:40:01.343373+00:00 app[web.1]: 10.101.131.90 - - [20/Feb/2015:05:39:55 +0000] "GET /callback.php?oauth_token=avaIQtW34x1epqFs67pPAd3MJBuoZnYP&oauth_verifier=2CI8qcn9IIRjKP9nl8CJUJsq7IvQOYmd HTTP/1.1" 500 - "https://api.twitter.com/oauth/authorize" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.53 Safari/537.36"
```

**Comment by EliuFlorez** [comment]
?

**Comment by abraham** [comment]
The demo just assumes that requests work without checking for success.

**Comment by rana07i** [comment]
how to display errors

**Comment by abraham** [comment]
TwitterOAuth is in maintenance mode and major improvements are no longer planned. https://github.com/abraham/twitteroauth/issues/1188
