### ISSUE TITLE
Uploading Animated GIF

### ISSUE THREAD

**Issue by novakben** [abraham/twitteroauth#499]
I'm trying to upload a locally saved animated gif with the example in the readme, but I get an error.
I can post statue without image fine. But this gets broken when trying to add the media. (media/upload).

```
PHP Fatal error:  Uncaught exception 'Abraham\TwitterOAuth\TwitterOAuthException' with message 'Operation timed out after 5074 milliseconds with 0 bytes received' in /Users/USERNAME/vendor/abraham/twitteroauth/src/TwitterOAuth.php:403
Stack trace:
#0 /Users/USERNAME/vendor/abraham/twitteroauth/src/TwitterOAuth.php(334): Abraham\TwitterOAuth\TwitterOAuth->request('https://upload....', 'POST', 'Authorization: ...', Array)
#1 /Users/USERNAME/vendor/abraham/twitteroauth/src/TwitterOAuth.php(305): Abraham\TwitterOAuth\TwitterOAuth->oAuthRequest('https://upload....', 'POST', Array)
#2 /Users/USERNAME/vendor/abraham/twitteroauth/src/TwitterOAuth.php(252): Abraham\TwitterOAuth\TwitterOAuth->http('POST', 'https://upload....', 'media/upload', Array)
#3 /Users/USERNAME/vendor/abraham/twitteroauth/src/TwitterOAuth.php(235): Abraham\TwitterOAuth\TwitterOAuth->uploadMediaNotChunked('media/upload', Array)
#4 /Users/USERNAME/uplaod.php(59): Abraham\TwitterOAuth\TwitterOAuth->upload('media/ in /Users/USERNAME/vendor/abraham/twitteroauth/src/TwitterOAuth.php on line 403
```

This is my source code:

```
//Upload GIF to twitter
$media1 = $connection->upload('media/upload', ['media' => 'gifs/upload.gif']);
print_r($media1);
```

**Comment by oussaki** [comment]
Check the media guide : https://dev.twitter.com/rest/media/uploading-media.html
it could be the size of your file or the Frames that your GIF file has , it should be less than 350 frames.

**Comment by abraham** [comment]
> Operation timed out after 5074 milliseconds

You can increase the timeouts TwitterOAuth uses with the following code:

```
$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, $access_token, $access_token_secret);
$connection->setTimeouts(10, 15);
```

The first number is how long to allow for connecting to api.twitter.com, the second number is the total time to allow.
