### ISSUE TITLE
HELP ME PLLLLLLLLLLLLLLZZZZZZZ I4M STUCK :'(

### ISSUE THREAD

**Issue by hacker-boy** [abraham/twitteroauth#524]
![capture](https://cloud.githubusercontent.com/assets/7106369/21180372/ee6f2bec-c1f8-11e6-88d8-46332c981cdd.PNG)
![capture2](https://cloud.githubusercontent.com/assets/7106369/21180373/ee91da70-c1f8-11e6-921d-3795c3f88778.PNG)

Fatal error: Uncaught Abraham\TwitterOAuth\TwitterOAuthException: error setting certificate verify locations: CAfile: C:\xampp\htdocs\Dropbox\LariWitter\src\ CApath: none in C:\xampp\htdocs\Dropbox\LariWitter\src\TwitterOAuth.php:408 Stack trace: #0 C:\xampp\htdocs\Dropbox\LariWitter\src\TwitterOAuth.php(334): Abraham\TwitterOAuth\TwitterOAuth->request('https://api.twi...', 'POST', 'Authorization: ...', Array) #1 C:\xampp\htdocs\Dropbox\LariWitter\src\TwitterOAuth.php(135): Abraham\TwitterOAuth\TwitterOAuth->oAuthRequest('https://api.twi...', 'POST', Array) #2 C:\xampp\htdocs\Dropbox\LariWitter\index.php(11): Abraham\TwitterOAuth\TwitterOAuth->oauth('oauth/request_t...', Array) #3 {main} thrown in C:\xampp\htdocs\Dropbox\LariWitter\src\TwitterOAuth.php on line 408

i have this problem i don't know why i keep getting this plz help me any one

**Comment by hacker-boy** [comment]
thanks i have found the solution الحمد لله :) the solution is to go to TwitterOAuth.php and make ssl_verfy=>false 
have a good day
