### ISSUE TITLE
Missing a step for "new TwitterOAuth()"

### ISSUE THREAD

**Issue by vikinggoat** [abraham/twitteroauth#662]
Not sure this is the right place to be asking for help with this, but I'm trying to figure out the current request methods of the new TwitterOAuth and I think I'm missing a step somewhere. 
Below you can see my script for initial contact with the Twitter servers but it seems to be failing.
$mapRootPath, $twAppID, and $twAppSec are brought through a require_once from another file.

```
require_once("twitteroauth/autoload.php");
use Abraham\TwitterOAuth\TwitterOAuth;
$returnUrl = $mapRootPath.'socialLogin.php?provider=twitter';

$twitterConnect = new TwitterOAuth($twAppID, $twAppSec);
$request_token = $twitterConnect->oauth("oauth/request_token", array("oauth_callback" => $returnUrl));

$_SESSION['oauth_token'] = $token = $request_token['oauth_token'];
$_SESSION['oauth_token_secret'] = $request_token['oauth_token_secret'];
// REDIRECTING TO THE URL
$url = $twitterConnect->url("oauth/authorize", array("oauth_token" => $request_token['oauth_token']));
```

**Comment by vikinggoat** [comment]
Is it perhaps necessary for the callback file be located in the same folder as autoload.php?

**Comment by vikinggoat** [comment]
If it help, I'm getting a 500 error and not much else.

**Comment by vikinggoat** [comment]
Oh yes of course, this seems to be the error thats showing up:
```
[01-Jul-2018 09:40:30 America/New_York] PHP Fatal error:  Uncaught Abraham\TwitterOAuth\TwitterOAuthException: error setting certificate verify locations:
  CAfile: /public_html/twitteroauth/src/cacert.pem
  CApath: none in /public_html/twitteroauth/src/TwitterOAuth.php:505
Stack trace:
#0 /public_html/twitteroauth/src/TwitterOAuth.php(422): Abraham\TwitterOAuth\TwitterOAuth->request('https://api.twi...', 'POST', 'Authorization: ...', Array)
#1 /public_html/twitteroauth/src/TwitterOAuth.php(165): Abraham\TwitterOAuth\TwitterOAuth->oAuthRequest('https://api.twi...', 'POST', Array)
#2 /public_html/twitterLogin.php(36): Abraham\TwitterOAuth\TwitterOAuth->oauth('oauth/request_t...', Array)
#3 /public_html/socialLogin.php(94): require_once('/public_html/twitterLogin.php')
#4 {main}
  thrown in /public_html/twitteroauth/src/TwitterOAuth.php on line 505
```

**Comment by abraham** [comment]
It looks like the `cacert.pem` file is missing from your code.
