### ISSUE TITLE
PHP 7.4 Array and string offset access syntax with curly braces is deprecated

### ISSUE THREAD

**Issue by roko91** [abraham/twitteroauth#797]
First thank you for the great package!

When testing PHP 7.4.0beta4 I encountered the following exception:

In HmacSha1.php line 15:

During class fetch: Uncaught ErrorException: Array and string offset access syntax with curly braces is deprecated in /home/test/test/vendor/abraham/twitteroauth/src/SignatureMethod.php:61                                                                
  Stack trace:                                                                                                                                  
  #0 /home/test/test/vendor/composer/ClassLoader.php(444): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
  #1 /home/test/test/vendor/composer/ClassLoader.php(444): include()
  #2 /home/test/test/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()
  #3 [internal function]: Composer\Autoload\ClassLoader->loadClass()
  #4 /home/test/test/vendor/abraham/twitteroauth/src/HmacSha1.php(15): spl_autoload_call()
  #5 /home/test/test/vendor/composer/ClassLoader.php(444): include('/home/test/tes...')
  #6 /home/test/test/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()
  #7

I think it's pretty self-explanatory - for array and string offset access curly braces should be replaced with square braces for future PHP versions.

I will create PR for this tomorrow.

**Comment by roko91** [comment]
Never mind I just saw someone else did already create PR: https://github.com/abraham/twitteroauth/pull/788
