### ISSUE TITLE
Proxy problem

### ISSUE THREAD

**Issue by pro-akour** [abraham/twitteroauth#944]
When I add a proxy

I have the following error

`Fatal error: Uncaught Abraham\TwitterOAuth\TwitterOAuthException: Failed connect to 67.227.35.130:3610; Connection refused in /home/***/public_html/src/TwitterOAuth.php:440 Stack trace: #0 /home/***/public_html/src/TwitterOAuth.php(357): Abraham\TwitterOAuth\TwitterOAuth->request('https://api.twi...', 'POST', 'Authorization: ...', Array) #1 /home/***/public_html/src/TwitterOAuth.php(134): Abraham\TwitterOAuth\TwitterOAuth->oAuthRequest('https://api.twi...', 'POST', Array) #2 /home/***/public_html/login.php(34): Abraham\TwitterOAuth\TwitterOAuth->oauth('oauth/request_t...', Array) #3 {main} thrown in /home/***/public_html/src/TwitterOAuth.php on line 440`

Note that I have added the data correctly
```
ip
user:pass
port
```

**Comment by pro-akour** [comment]
I have solved the problem.

I typed the code incorrectly

The error
```
$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET);
$connection->setProxy([
    'CURLOPT_PROXY' => '127.0.0.0',
    'CURLOPT_PROXYUSERPWD' => '',
    'CURLOPT_PROXYPORT' => 8080,
]);
```


The solution

```
$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, $access_token, $access_token_secret);
$connection->setProxy([
    'CURLOPT_PROXY' => '127.0.0.0',
    'CURLOPT_PROXYUSERPWD' => '',
    'CURLOPT_PROXYPORT' => 8080,
]);
```
