### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Composer\CaBundle\CaBundle' not found

### ISSUE THREAD

**Issue by TylerMWise** [abraham/twitteroauth#966]
Hi, I am getting this error when I am trying to use the API, I have the lib installed and I haven't touched anything but I get told:

```
Fatal error: Uncaught Error: Class 'Composer\CaBundle\CaBundle' not found in /homepages/27/d661165336/htdocs/tyler/vendor/src/TwitterOAuth.php:572 Stack trace: #0 /homepages/27/d661165336/htdocs/tyler/vendor/src/TwitterOAuth.php(620): Abraham\TwitterOAuth\TwitterOAuth->curlOptions() #1 /homepages/27/d661165336/htdocs/tyler/vendor/src/TwitterOAuth.php(557): Abraham\TwitterOAuth\TwitterOAuth->request('https://api.twi...', 'GET', 'Authorization: ...', Array, false) #2 /homepages/27/d661165336/htdocs/tyler/vendor/src/TwitterOAuth.php(490): Abraham\TwitterOAuth\TwitterOAuth->oAuthRequest('https://api.twi...', 'GET', Array, false) #3 /homepages/27/d661165336/htdocs/tyler/vendor/src/TwitterOAuth.php(467): Abraham\TwitterOAuth\TwitterOAuth->makeRequests('https://api.twi...', 'GET', Array, false) #4 /homepages/27/d661165336/htdocs/tyler/vendor/src/TwitterOAuth.php(232): Abraham\TwitterOAuth\TwitterOAuth->http('GET', 'https://api.twi...', 'account/verify_...', Array, false) #5 /homepages/27/d661165336/htdocs/tyler/code.php(12): Abr in /homepages/27/d661165336/htdocs/tyler/vendor/src/TwitterOAuth.php on line 572
```

The code I am using is:
```php
<?php
require_once "vendor/autoload.php";
 
use Abraham\TwitterOAuth\TwitterOAuth;
 
define('CONSUMER_KEY', 'hidden_for_here');
define('CONSUMER_SECRET', 'hidden_for_here');
define('ACCESS_TOKEN', 'hidden_for_here');
define('ACCESS_TOKEN_SECRET', 'hidden_for_here');
$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, ACCESS_TOKEN, ACCESS_TOKEN_SECRET);

$content = $connection->get("account/verify_credentials");
$statues = $connection->post("statuses/update", ["status" => "hello world"]);
```

Could anyone help?

**Comment by abraham** [comment]
It looks like you CaBundle isn't installed. Make sure you run `composer install`.

**Comment by TylerMWise** [comment]
Ah yeah, it's fixed now thanks
